using DSSL.Blog.Comments;
using DSSL.Blog.Posts;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Volo.Abp.Data;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Domain.Repositories;
using Volo.Abp.Guids;
using Volo.Abp.Identity;

namespace DSSL.Blog
{
    public class BlogDataSeederContributor : IDataSeedContributor, ITransientDependency
    {
        private readonly IRepository<Post, Guid> _postRepository;
        private readonly IRepository<Comment, Guid> _commentRepository;
        private readonly IRepository<IdentityUser, Guid> _userRepository;
        private readonly IGuidGenerator _guidGenerator;

        public BlogDataSeederContributor(IRepository<Post, Guid> postRepository, IRepository<Comment, Guid> commentRepository, IRepository<IdentityUser, Guid> userRepository, IGuidGenerator guidGenerator)
        {
            _postRepository = postRepository;
            _commentRepository = commentRepository;
            _userRepository = userRepository;
            _guidGenerator = guidGenerator;
        }

        public async Task SeedAsync(DataSeedContext context)
        {
            var author = await _userRepository.FirstOrDefaultAsync();
            var posts = await CreatePostsAsync(author.Id);

            foreach (var post in posts)
            {
                await CreateCommentsAsync(post);
            }
        }

        private async Task CreateCommentsAsync(Post post)
        {
            var random = new Random().Next(0, 10);
            var comments = new List<Comment>();

            for (var i = 0; i < random; i++)
            {
                var message = LoremIpsum(0, 25, 0, 4, 2);
                var comment = new Comment(_guidGenerator.Create(), message, post.Id);
                comments.Add(comment);
            }

            await _commentRepository.InsertManyAsync(comments);
        }

        private async Task<IEnumerable<Post>> CreatePostsAsync(Guid authorId)
        {
            var posts = new List<Post>
            {
                new(_guidGenerator.Create(),
                    "Post 1",
                    "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANGUlEQVR4nOzXDa8W9H3GcY8eH1qriIptsVKLdSUore1GtEe0M1WnRpxsYG1cFKHRdU4rTZnHKOJqzWprF9bgWFOinXvCwsB1sHazDUVS6ApzXVcWwYoyGfIkWjhN0YLuVVxJk+vzeQHX/w7c8L1/g3fee+iIpGuPuCm6P/L2udH9pw/Piu5ff+o7o/tjL/y96P7fLx8d3b/6LyZE9z9/4Lbo/t1TLoruf2/SQHR/6Ef/GN1fM39DdH/XD46L7j8zMim6f9T6e6P7R0bXAfi1JQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASg08vfSq6AMb9yyM7u85567o/pS9N0T3PzRqVXT/zplro/sjOzdG96+Z9qvo/m/c/J3o/g9HbYvuL7zsuej+sqHZ0f3PnXBedP/Cpb8T3d+7+M+i+/s/vSO67wIAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoNTFg3FH1gy39eEN2f89zF0f1Pzj4/uv/Zz1wa3X/o5rnR/Rt//NPo/ivzFkT3D57wWHT/T75xeXT/0iemRffnrr49un/yqMnR/T/9r/3R/YkHfzu6f+r9S6L7LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNTg/76wIPrAxO0ro/v/tO+66P7mk06N7m8cvTq6v27eu6P7b8z9RHT/pTPfG90fuzD79/vLNQ9H9095eXd0/4tXZ38jnjR8YXT/khW3RPcHv39rdH/LSPb77wIAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoN/u11T0UfuOGcN6L7+855NLp/9M8+H90/5cat0f27Fs6N7s9f/3B0//1XXxvdn/iVmdH9xZuHovtDXz8U3Z/87Nuj+yPPj4nuTz3m/dH95Y9/OLr/0GWfju67AABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgMvLf9B9IGjt82O7q9ZfWJ0f/j47P6a67dH96/+wL7o/hc++e3o/pvL9kT39/5yY3R/7k3/Ht2fcWBzdP+K01dE97+58Nbo/pL3fSS6v+6ikej+cWffEt13AQCUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQb/9bSjow8cvuuPo/u7/vnD0f3Xll4Z3V/5wAej+4tePRTd/6MxH4/u3/3W6dH9D85aHd2/e+yZ0f3RX1gc3R/3yHnR/Z/POD66P/zymOj+yrHD0f3bTr8guu8CACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKDXzjqxuiD1yy/ozo/k8mzYzu3/elU6L7v3vLiuj+jxcMRPdvfuTY6P61z4yN7j+8ZXp0f+WcMdH943afHd0fu3RmdH/TZdn97/7+5Oj+0bNWRfc3HzUY3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBn+2YEL0gXv2bozun/jDp6L7Y198MLp/xhHZP/9dX9kc3b/jtXui+2dszH7+K3ePj+7/dNWs6P4Tky+N7l/06Nei+xu2LInuv2vG1Oj+f4+8J7p/x7js53cBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBrZOfTT6wP9M/5vo/sS3zo/uX/bsndH91cNXRPc3HLwjun/55Kej+1On/VZ0/8s3XRLdn3Dm9dH9G869O7r/ucOPRfdfP+q26P4fbt0R3V+/YnR0/4R7p0f3XQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQKnBZ76/KPrAvOUnR/fPGnNtdP997z4Q3V93+svR/cdv+Ux0f/+n1kf3H7piUnT/N9eMj+5/8cQHovvjvvWT6P6o2/8uun/frcdE96eNy/77mv7eF6P7b771cHTfBQBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBo495Vnow8MT7snuv+J7Xuj+x+9fHR0/zuTvxzd/8A1m6P7/7L436L71702Pbp/7KJTo/vz18+J7r96+4zo/v2Tvh3dX/up5dH9bauz3599E3ZH9x/bmf3/zQUAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQavH38pugDr8++Mrp/1qGvRvdHTtoW3V81+I7o/vAFt0X3Z7/tmOj+P8xaEN1fdPZ50f35ry+P7j80bn50/1vD90X3v3Ta9uj+0P/tjO5/7P4p0f3x77k4uu8CACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKDQ6N3xN9YMqlj0T3d37tQ9H9y0fPiu7vH/p6dH/ZO9+M7v/lq+dG95eNrI3ub/p59vu/euqc6P6iPQ9G92+8Zji6v+c/Phvdv/nJA9H9ladlv//zLtoU3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBmfOGIw+cNeTj0b3J/9iKLr/+DfHRPd/8aPD0f13PP+96P4ffPTY6P6uF74b3X/XHROj+6Pu/0h0f9bgG9H9KW/76+j+E2vPju6f/MDB6P6+JTuj+2sWrYzuuwAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFKDL+3/WPSBPz/8YnT/0KGPR/fvPP786P69V2U//7ojN0f3J77wZHT/Vw/siO5vX7Yvuj+w6MHo/pz1J0f3L/6rV6L7zx+Z/Q161t6rovtPbX0uur9j8bzovgsAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACj1/wEAAP//MM2BW6cAiRoAAAAASUVORK5CYII=",
                    true,
                    new List<string>
                    {
                        "Tech",
                        "Food"
                    }),

                 new(_guidGenerator.Create(),
                    "Post 2",
                    "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANGUlEQVR4nOzXDa8W9H3GcY8eH1qriIptsVKLdSUore1GtEe0M1WnRpxsYG1cFKHRdU4rTZnHKOJqzWprF9bgWFOinXvCwsB1sHazDUVS6ApzXVcWwYoyGfIkWjhN0YLuVVxJk+vzeQHX/w7c8L1/g3fee+iIpGuPuCm6P/L2udH9pw/Piu5ff+o7o/tjL/y96P7fLx8d3b/6LyZE9z9/4Lbo/t1TLoruf2/SQHR/6Ef/GN1fM39DdH/XD46L7j8zMim6f9T6e6P7R0bXAfi1JQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASg08vfSq6AMb9yyM7u85567o/pS9N0T3PzRqVXT/zplro/sjOzdG96+Z9qvo/m/c/J3o/g9HbYvuL7zsuej+sqHZ0f3PnXBedP/Cpb8T3d+7+M+i+/s/vSO67wIAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoNTFg3FH1gy39eEN2f89zF0f1Pzj4/uv/Zz1wa3X/o5rnR/Rt//NPo/ivzFkT3D57wWHT/T75xeXT/0iemRffnrr49un/yqMnR/T/9r/3R/YkHfzu6f+r9S6L7LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNTg/76wIPrAxO0ro/v/tO+66P7mk06N7m8cvTq6v27eu6P7b8z9RHT/pTPfG90fuzD79/vLNQ9H9095eXd0/4tXZ38jnjR8YXT/khW3RPcHv39rdH/LSPb77wIAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoN/u11T0UfuOGcN6L7+855NLp/9M8+H90/5cat0f27Fs6N7s9f/3B0//1XXxvdn/iVmdH9xZuHovtDXz8U3Z/87Nuj+yPPj4nuTz3m/dH95Y9/OLr/0GWfju67AABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgMvLf9B9IGjt82O7q9ZfWJ0f/j47P6a67dH96/+wL7o/hc++e3o/pvL9kT39/5yY3R/7k3/Ht2fcWBzdP+K01dE97+58Nbo/pL3fSS6v+6ikej+cWffEt13AQCUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQb/9bSjow8cvuuPo/u7/vnD0f3Xll4Z3V/5wAej+4tePRTd/6MxH4/u3/3W6dH9D85aHd2/e+yZ0f3RX1gc3R/3yHnR/Z/POD66P/zymOj+yrHD0f3bTr8guu8CACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKDXzjqxuiD1yy/ozo/k8mzYzu3/elU6L7v3vLiuj+jxcMRPdvfuTY6P61z4yN7j+8ZXp0f+WcMdH943afHd0fu3RmdH/TZdn97/7+5Oj+0bNWRfc3HzUY3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBn+2YEL0gXv2bozun/jDp6L7Y198MLp/xhHZP/9dX9kc3b/jtXui+2dszH7+K3ePj+7/dNWs6P4Tky+N7l/06Nei+xu2LInuv2vG1Oj+f4+8J7p/x7js53cBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBrZOfTT6wP9M/5vo/sS3zo/uX/bsndH91cNXRPc3HLwjun/55Kej+1On/VZ0/8s3XRLdn3Dm9dH9G869O7r/ucOPRfdfP+q26P4fbt0R3V+/YnR0/4R7p0f3XQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQKnBZ76/KPrAvOUnR/fPGnNtdP997z4Q3V93+svR/cdv+Ux0f/+n1kf3H7piUnT/N9eMj+5/8cQHovvjvvWT6P6o2/8uun/frcdE96eNy/77mv7eF6P7b771cHTfBQBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBo495Vnow8MT7snuv+J7Xuj+x+9fHR0/zuTvxzd/8A1m6P7/7L436L71702Pbp/7KJTo/vz18+J7r96+4zo/v2Tvh3dX/up5dH9bauz3599E3ZH9x/bmf3/zQUAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQavH38pugDr8++Mrp/1qGvRvdHTtoW3V81+I7o/vAFt0X3Z7/tmOj+P8xaEN1fdPZ50f35ry+P7j80bn50/1vD90X3v3Ta9uj+0P/tjO5/7P4p0f3x77k4uu8CACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKDQ6N3xN9YMqlj0T3d37tQ9H9y0fPiu7vH/p6dH/ZO9+M7v/lq+dG95eNrI3ub/p59vu/euqc6P6iPQ9G92+8Zji6v+c/Phvdv/nJA9H9ladlv//zLtoU3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBmfOGIw+cNeTj0b3J/9iKLr/+DfHRPd/8aPD0f13PP+96P4ffPTY6P6uF74b3X/XHROj+6Pu/0h0f9bgG9H9KW/76+j+E2vPju6f/MDB6P6+JTuj+2sWrYzuuwAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFKDL+3/WPSBPz/8YnT/0KGPR/fvPP786P69V2U//7ojN0f3J77wZHT/Vw/siO5vX7Yvuj+w6MHo/pz1J0f3L/6rV6L7zx+Z/Q161t6rovtPbX0uur9j8bzovgsAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACj1/wEAAP//MM2BW6cAiRoAAAAASUVORK5CYII=",
                    false,
                    new List<string>
                    {
                        "Baby",
                        "Food"
                    }),
                  new(_guidGenerator.Create(),
                    "Post 3",
                    "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANGUlEQVR4nOzXDa8W9H3GcY8eH1qriIptsVKLdSUore1GtEe0M1WnRpxsYG1cFKHRdU4rTZnHKOJqzWprF9bgWFOinXvCwsB1sHazDUVS6ApzXVcWwYoyGfIkWjhN0YLuVVxJk+vzeQHX/w7c8L1/g3fee+iIpGuPuCm6P/L2udH9pw/Piu5ff+o7o/tjL/y96P7fLx8d3b/6LyZE9z9/4Lbo/t1TLoruf2/SQHR/6Ef/GN1fM39DdH/XD46L7j8zMim6f9T6e6P7R0bXAfi1JQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASg08vfSq6AMb9yyM7u85567o/pS9N0T3PzRqVXT/zplro/sjOzdG96+Z9qvo/m/c/J3o/g9HbYvuL7zsuej+sqHZ0f3PnXBedP/Cpb8T3d+7+M+i+/s/vSO67wIAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoNTFg3FH1gy39eEN2f89zF0f1Pzj4/uv/Zz1wa3X/o5rnR/Rt//NPo/ivzFkT3D57wWHT/T75xeXT/0iemRffnrr49un/yqMnR/T/9r/3R/YkHfzu6f+r9S6L7LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNTg/76wIPrAxO0ro/v/tO+66P7mk06N7m8cvTq6v27eu6P7b8z9RHT/pTPfG90fuzD79/vLNQ9H9095eXd0/4tXZ38jnjR8YXT/khW3RPcHv39rdH/LSPb77wIAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoN/u11T0UfuOGcN6L7+855NLp/9M8+H90/5cat0f27Fs6N7s9f/3B0//1XXxvdn/iVmdH9xZuHovtDXz8U3Z/87Nuj+yPPj4nuTz3m/dH95Y9/OLr/0GWfju67AABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgMvLf9B9IGjt82O7q9ZfWJ0f/j47P6a67dH96/+wL7o/hc++e3o/pvL9kT39/5yY3R/7k3/Ht2fcWBzdP+K01dE97+58Nbo/pL3fSS6v+6ikej+cWffEt13AQCUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQb/9bSjow8cvuuPo/u7/vnD0f3Xll4Z3V/5wAej+4tePRTd/6MxH4/u3/3W6dH9D85aHd2/e+yZ0f3RX1gc3R/3yHnR/Z/POD66P/zymOj+yrHD0f3bTr8guu8CACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKDXzjqxuiD1yy/ozo/k8mzYzu3/elU6L7v3vLiuj+jxcMRPdvfuTY6P61z4yN7j+8ZXp0f+WcMdH943afHd0fu3RmdH/TZdn97/7+5Oj+0bNWRfc3HzUY3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBn+2YEL0gXv2bozun/jDp6L7Y198MLp/xhHZP/9dX9kc3b/jtXui+2dszH7+K3ePj+7/dNWs6P4Tky+N7l/06Nei+xu2LInuv2vG1Oj+f4+8J7p/x7js53cBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBrZOfTT6wP9M/5vo/sS3zo/uX/bsndH91cNXRPc3HLwjun/55Kej+1On/VZ0/8s3XRLdn3Dm9dH9G869O7r/ucOPRfdfP+q26P4fbt0R3V+/YnR0/4R7p0f3XQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQKnBZ76/KPrAvOUnR/fPGnNtdP997z4Q3V93+svR/cdv+Ux0f/+n1kf3H7piUnT/N9eMj+5/8cQHovvjvvWT6P6o2/8uun/frcdE96eNy/77mv7eF6P7b771cHTfBQBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBo495Vnow8MT7snuv+J7Xuj+x+9fHR0/zuTvxzd/8A1m6P7/7L436L71702Pbp/7KJTo/vz18+J7r96+4zo/v2Tvh3dX/up5dH9bauz3599E3ZH9x/bmf3/zQUAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQavH38pugDr8++Mrp/1qGvRvdHTtoW3V81+I7o/vAFt0X3Z7/tmOj+P8xaEN1fdPZ50f35ry+P7j80bn50/1vD90X3v3Ta9uj+0P/tjO5/7P4p0f3x77k4uu8CACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKDQ6N3xN9YMqlj0T3d37tQ9H9y0fPiu7vH/p6dH/ZO9+M7v/lq+dG95eNrI3ub/p59vu/euqc6P6iPQ9G92+8Zji6v+c/Phvdv/nJA9H9ladlv//zLtoU3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBmfOGIw+cNeTj0b3J/9iKLr/+DfHRPd/8aPD0f13PP+96P4ffPTY6P6uF74b3X/XHROj+6Pu/0h0f9bgG9H9KW/76+j+E2vPju6f/MDB6P6+JTuj+2sWrYzuuwAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFKDL+3/WPSBPz/8YnT/0KGPR/fvPP786P69V2U//7ojN0f3J77wZHT/Vw/siO5vX7Yvuj+w6MHo/pz1J0f3L/6rV6L7zx+Z/Q161t6rovtPbX0uur9j8bzovgsAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACj1/wEAAP//MM2BW6cAiRoAAAAASUVORK5CYII=",
                    true,
                    new List<string>
                    {
                        "Tech",
                        "Smart"
                    }),
                   new(_guidGenerator.Create(),
                    "Post 4",
                    "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANGUlEQVR4nOzXDa8W9H3GcY8eH1qriIptsVKLdSUore1GtEe0M1WnRpxsYG1cFKHRdU4rTZnHKOJqzWprF9bgWFOinXvCwsB1sHazDUVS6ApzXVcWwYoyGfIkWjhN0YLuVVxJk+vzeQHX/w7c8L1/g3fee+iIpGuPuCm6P/L2udH9pw/Piu5ff+o7o/tjL/y96P7fLx8d3b/6LyZE9z9/4Lbo/t1TLoruf2/SQHR/6Ef/GN1fM39DdH/XD46L7j8zMim6f9T6e6P7R0bXAfi1JQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASg08vfSq6AMb9yyM7u85567o/pS9N0T3PzRqVXT/zplro/sjOzdG96+Z9qvo/m/c/J3o/g9HbYvuL7zsuej+sqHZ0f3PnXBedP/Cpb8T3d+7+M+i+/s/vSO67wIAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoNTFg3FH1gy39eEN2f89zF0f1Pzj4/uv/Zz1wa3X/o5rnR/Rt//NPo/ivzFkT3D57wWHT/T75xeXT/0iemRffnrr49un/yqMnR/T/9r/3R/YkHfzu6f+r9S6L7LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNTg/76wIPrAxO0ro/v/tO+66P7mk06N7m8cvTq6v27eu6P7b8z9RHT/pTPfG90fuzD79/vLNQ9H9095eXd0/4tXZ38jnjR8YXT/khW3RPcHv39rdH/LSPb77wIAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoN/u11T0UfuOGcN6L7+855NLp/9M8+H90/5cat0f27Fs6N7s9f/3B0//1XXxvdn/iVmdH9xZuHovtDXz8U3Z/87Nuj+yPPj4nuTz3m/dH95Y9/OLr/0GWfju67AABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgMvLf9B9IGjt82O7q9ZfWJ0f/j47P6a67dH96/+wL7o/hc++e3o/pvL9kT39/5yY3R/7k3/Ht2fcWBzdP+K01dE97+58Nbo/pL3fSS6v+6ikej+cWffEt13AQCUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQb/9bSjow8cvuuPo/u7/vnD0f3Xll4Z3V/5wAej+4tePRTd/6MxH4/u3/3W6dH9D85aHd2/e+yZ0f3RX1gc3R/3yHnR/Z/POD66P/zymOj+yrHD0f3bTr8guu8CACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKDXzjqxuiD1yy/ozo/k8mzYzu3/elU6L7v3vLiuj+jxcMRPdvfuTY6P61z4yN7j+8ZXp0f+WcMdH943afHd0fu3RmdH/TZdn97/7+5Oj+0bNWRfc3HzUY3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBn+2YEL0gXv2bozun/jDp6L7Y198MLp/xhHZP/9dX9kc3b/jtXui+2dszH7+K3ePj+7/dNWs6P4Tky+N7l/06Nei+xu2LInuv2vG1Oj+f4+8J7p/x7js53cBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBrZOfTT6wP9M/5vo/sS3zo/uX/bsndH91cNXRPc3HLwjun/55Kej+1On/VZ0/8s3XRLdn3Dm9dH9G869O7r/ucOPRfdfP+q26P4fbt0R3V+/YnR0/4R7p0f3XQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQKnBZ76/KPrAvOUnR/fPGnNtdP997z4Q3V93+svR/cdv+Ux0f/+n1kf3H7piUnT/N9eMj+5/8cQHovvjvvWT6P6o2/8uun/frcdE96eNy/77mv7eF6P7b771cHTfBQBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBo495Vnow8MT7snuv+J7Xuj+x+9fHR0/zuTvxzd/8A1m6P7/7L436L71702Pbp/7KJTo/vz18+J7r96+4zo/v2Tvh3dX/up5dH9bauz3599E3ZH9x/bmf3/zQUAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQavH38pugDr8++Mrp/1qGvRvdHTtoW3V81+I7o/vAFt0X3Z7/tmOj+P8xaEN1fdPZ50f35ry+P7j80bn50/1vD90X3v3Ta9uj+0P/tjO5/7P4p0f3x77k4uu8CACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKDQ6N3xN9YMqlj0T3d37tQ9H9y0fPiu7vH/p6dH/ZO9+M7v/lq+dG95eNrI3ub/p59vu/euqc6P6iPQ9G92+8Zji6v+c/Phvdv/nJA9H9ladlv//zLtoU3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBmfOGIw+cNeTj0b3J/9iKLr/+DfHRPd/8aPD0f13PP+96P4ffPTY6P6uF74b3X/XHROj+6Pu/0h0f9bgG9H9KW/76+j+E2vPju6f/MDB6P6+JTuj+2sWrYzuuwAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFKDL+3/WPSBPz/8YnT/0KGPR/fvPP786P69V2U//7ojN0f3J77wZHT/Vw/siO5vX7Yvuj+w6MHo/pz1J0f3L/6rV6L7zx+Z/Q161t6rovtPbX0uur9j8bzovgsAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACj1/wEAAP//MM2BW6cAiRoAAAAASUVORK5CYII=",
                    true,
                    new List<string>()
                   ),
                    new(_guidGenerator.Create(),
                    "Post 5",
                    "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAANGUlEQVR4nOzXDa8W9H3GcY8eH1qriIptsVKLdSUore1GtEe0M1WnRpxsYG1cFKHRdU4rTZnHKOJqzWprF9bgWFOinXvCwsB1sHazDUVS6ApzXVcWwYoyGfIkWjhN0YLuVVxJk+vzeQHX/w7c8L1/g3fee+iIpGuPuCm6P/L2udH9pw/Piu5ff+o7o/tjL/y96P7fLx8d3b/6LyZE9z9/4Lbo/t1TLoruf2/SQHR/6Ef/GN1fM39DdH/XD46L7j8zMim6f9T6e6P7R0bXAfi1JQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASg08vfSq6AMb9yyM7u85567o/pS9N0T3PzRqVXT/zplro/sjOzdG96+Z9qvo/m/c/J3o/g9HbYvuL7zsuej+sqHZ0f3PnXBedP/Cpb8T3d+7+M+i+/s/vSO67wIAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoNTFg3FH1gy39eEN2f89zF0f1Pzj4/uv/Zz1wa3X/o5rnR/Rt//NPo/ivzFkT3D57wWHT/T75xeXT/0iemRffnrr49un/yqMnR/T/9r/3R/YkHfzu6f+r9S6L7LgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoNTg/76wIPrAxO0ro/v/tO+66P7mk06N7m8cvTq6v27eu6P7b8z9RHT/pTPfG90fuzD79/vLNQ9H9095eXd0/4tXZ38jnjR8YXT/khW3RPcHv39rdH/LSPb77wIAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoN/u11T0UfuOGcN6L7+855NLp/9M8+H90/5cat0f27Fs6N7s9f/3B0//1XXxvdn/iVmdH9xZuHovtDXz8U3Z/87Nuj+yPPj4nuTz3m/dH95Y9/OLr/0GWfju67AABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgMvLf9B9IGjt82O7q9ZfWJ0f/j47P6a67dH96/+wL7o/hc++e3o/pvL9kT39/5yY3R/7k3/Ht2fcWBzdP+K01dE97+58Nbo/pL3fSS6v+6ikej+cWffEt13AQCUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQb/9bSjow8cvuuPo/u7/vnD0f3Xll4Z3V/5wAej+4tePRTd/6MxH4/u3/3W6dH9D85aHd2/e+yZ0f3RX1gc3R/3yHnR/Z/POD66P/zymOj+yrHD0f3bTr8guu8CACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKDXzjqxuiD1yy/ozo/k8mzYzu3/elU6L7v3vLiuj+jxcMRPdvfuTY6P61z4yN7j+8ZXp0f+WcMdH943afHd0fu3RmdH/TZdn97/7+5Oj+0bNWRfc3HzUY3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBn+2YEL0gXv2bozun/jDp6L7Y198MLp/xhHZP/9dX9kc3b/jtXui+2dszH7+K3ePj+7/dNWs6P4Tky+N7l/06Nei+xu2LInuv2vG1Oj+f4+8J7p/x7js53cBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBrZOfTT6wP9M/5vo/sS3zo/uX/bsndH91cNXRPc3HLwjun/55Kej+1On/VZ0/8s3XRLdn3Dm9dH9G869O7r/ucOPRfdfP+q26P4fbt0R3V+/YnR0/4R7p0f3XQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQKnBZ76/KPrAvOUnR/fPGnNtdP997z4Q3V93+svR/cdv+Ux0f/+n1kf3H7piUnT/N9eMj+5/8cQHovvjvvWT6P6o2/8uun/frcdE96eNy/77mv7eF6P7b771cHTfBQBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBo495Vnow8MT7snuv+J7Xuj+x+9fHR0/zuTvxzd/8A1m6P7/7L436L71702Pbp/7KJTo/vz18+J7r96+4zo/v2Tvh3dX/up5dH9bauz3599E3ZH9x/bmf3/zQUAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQavH38pugDr8++Mrp/1qGvRvdHTtoW3V81+I7o/vAFt0X3Z7/tmOj+P8xaEN1fdPZ50f35ry+P7j80bn50/1vD90X3v3Ta9uj+0P/tjO5/7P4p0f3x77k4uu8CACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKDQ6N3xN9YMqlj0T3d37tQ9H9y0fPiu7vH/p6dH/ZO9+M7v/lq+dG95eNrI3ub/p59vu/euqc6P6iPQ9G92+8Zji6v+c/Phvdv/nJA9H9ladlv//zLtoU3XcBAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBmfOGIw+cNeTj0b3J/9iKLr/+DfHRPd/8aPD0f13PP+96P4ffPTY6P6uF74b3X/XHROj+6Pu/0h0f9bgG9H9KW/76+j+E2vPju6f/MDB6P6+JTuj+2sWrYzuuwAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFKDL+3/WPSBPz/8YnT/0KGPR/fvPP786P69V2U//7ojN0f3J77wZHT/Vw/siO5vX7Yvuj+w6MHo/pz1J0f3L/6rV6L7zx+Z/Q161t6rovtPbX0uur9j8bzovgsAoJQAAJQSAIBSAgBQSgAASgkAQCkBACglAAClBACglAAAlBIAgFICAFBKAABKCQBAKQEAKCUAAKUEAKCUAACUEgCAUgIAUEoAAEoJAEApAQAoJQAApQQAoJQAAJQSAIBSAgBQSgAASgkAQCkBACj1/wEAAP//MM2BW6cAiRoAAAAASUVORK5CYII=",
                    false,
                    new List<string>()
                    )
            };

            await _postRepository.InsertManyAsync(posts);

            return posts;
        }

        private static string LoremIpsum(int minWords, int maxWords, int minSentences, int maxSentences, int numParagraphs)
        {

            var words = new[]{"lorem", "ipsum", "dolor", "sit", "amet", "consectetuer",
                "adipiscing", "elit", "sed", "diam", "nonummy", "nibh", "euismod",
                "tincidunt", "ut", "laoreet", "dolore", "magna", "aliquam", "erat"};

            var random = new Random();
            var sentences = random.Next(maxSentences - minSentences)
                               + minSentences + 1;
            var wordIndex = random.Next(maxWords - minWords) + minWords + 1;

            var result = new StringBuilder();

            for (var p = 0; p < numParagraphs; p++)
            {
                result.Append("<p>");
                for (var s = 0; s < sentences; s++)
                {
                    for (var w = 0; w < wordIndex; w++)
                    {
                        if (w > 0) { result.Append(' '); }
                        result.Append(words[random.Next(words.Length)]);
                    }
                    result.Append(". ");
                }
                result.Append("</p>");
            }

            return result.ToString();
        }
    }
}
